module.exports = {
  displayName: 'journeyLogs',
  preset: '@testing-library/react-native',
  testRunner: 'jest-jasmine2',
  moduleFileExtensions: ['ts', 'js', 'html', 'tsx', 'jsx'],
  setupFilesAfterEnv: ['<rootDir>/src/config/test.config.ts'],
  setupFiles: ['./node_modules/react-native-gesture-handler/jestSetup.js'],
  moduleNameMapper: {
    '^@sz/assets(.*)$': '<rootDir>/src/assets$1',
    '^@sz/components(.*)$': '<rootDir>/src/components$1',
    '^@sz/config(.*)$': '<rootDir>/src/config$1',
    '^@sz/constants(.*)$': '<rootDir>/src/constants$1',
    '^@sz/hooks(.*)$': '<rootDir>/src/hooks$1',
    '^@sz/models(.*)$': '<rootDir>/src/models$1',
    '^@sz/navigation(.*)$': '<rootDir>/src/navigation$1',
    '^@sz/screens(.*)$': '<rootDir>/src/screens$1',
    '^@sz/services(.*)$': '<rootDir>/src/services$1',
    '^@sz/stores(.*)$': '<rootDir>/src/stores$1',
    '^@sz/utils(.*)$': '<rootDir>/src/utils$1',
  },
  transform: {
    '/node_modules/.+\\.(js|ts|tsx)$': './react-native-jest-preprocessor.js',
    '\\.(js|ts|tsx)$': 'ts-jest',
    '^.+\\.jsx?$': 'babel-jest',
    '^.+\\.(ts|tsx)?$': 'ts-jest',
    // '\\.(js|ts|tsx)$': 'ts-jest',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|@react-native|@react-navigation|@react-native-firebase/auth)|react-native-pell-rich-editor',
  ],
};
