export enum Route {
  AuthStack = 'auth-stack',
  CalendarTab = 'calendar-tab',
  ChangePinCode = 'change-pin-code',
  ConfirmPinCode = 'confirm-pin-code',
  EditNote = 'edit-note',
  ForgetPassword = 'forget-password',
  HiddenNotes = 'hidden-notes',
  HomeTab = 'home-tab',
  Login = 'login',
  LoginStack = 'login-stack',
  MainBottomTabRoutesStack = 'main-bottom-tab-routes-stack',
  MainStack = 'main-stack',
  MaxPinCodeAttemptsReached = 'max-pin-code-attempts-reached',
  NewNoteTab = 'new-note-tab',
  NotesStack = 'notes-stack',
  OldPINVerification = 'old-pin-verification',
  PinCode = 'pin-code',
  PlaceHolderRoute = 'place-holder-route',
  PreviewNote = 'preview-note',
  SearchTab = 'search-tab',
  SettingsStack = 'settings-stack',
  SettingsTab = 'settings-tab',
  Signup = 'sign-up',
  SignupStack = 'sign-up-stack',
  Tags = 'tags',
}
