export enum Route {
  AuthStack = 'auth-stack',
  CalendarTab = 'calendar-tab',
  EditorStack = 'editor-stack',
  EditorTab = 'editor-tab',
  PlaceHolderRoute = 'place-holder-route',
  HomeTab = 'home-tab',
  Login = 'login',
  LoginStack = 'login-stack',
  MainBottomTabRoutesStack = 'main-bottom-tab-routes-stack',
  MainStack = 'main-stack',
  SearchTab = 'search-tab',
  SettingsTab = 'settings-tab',
  Signup = 'sign-up',
  SignupStack = 'sign-up-stack',
}
