export enum Route {
  AuthStack = 'auth-stack',
  CalendarTab = 'calendar-tab',
  EditNote = 'edit-note',
  ForgetPassword = 'forget-password',
  HomeTab = 'home-tab',
  Login = 'login',
  LoginStack = 'login-stack',
  MainBottomTabRoutesStack = 'main-bottom-tab-routes-stack',
  MainStack = 'main-stack',
  NewNoteTab = 'new-note-tab',
  NotesStack = 'notes-stack',
  PlaceHolderRoute = 'place-holder-route',
  PreviewNote = 'preview-note',
  SearchTab = 'search-tab',
  SettingsTab = 'settings-tab',
  Signup = 'sign-up',
  SignupStack = 'sign-up-stack',
}
